# LetterOn Server - Docker Compose
# Purpose: Local development environment with Docker
# Testing: docker-compose up
# AWS Deployment: Not used in production (ECS/Fargate handles orchestration)

version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Mount code for hot reload in development
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Add DynamoDB Local for testing
  # dynamodb-local:
  #   image: amazon/dynamodb-local:latest
  #   ports:
  #     - "8001:8000"
  #   command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
  #   restart: unless-stopped
